# Site settings
title: Zack Cram
email: zmcram@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "zackcram.github.io" # the base hostname & protocol for your site
github_username:  zackcram

defaults:
	-
		scope:
			path:	""
			type:	"posts"
		values:
			author: Zack Cram
			layout:	"post"
			category: 	blog
			comments:	true
	-
		scope:
			path:	""
			type:	"pages"
			values:
			layout:	"page"


# Build settings
markdown: kramdown
permalink: /:title
